//
//  MainModels.swift
//  SpaceX Launches
//
//  Created by Vlad Ralovich on 5.04.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        enum RequestType {
            case getSpaceRocket
            case saveMetterings(isHeightM: Bool, isWidthM: Bool, isMassKg: Bool, isPayloadKg: Bool)
        }
    }
    struct Response
    {
        enum ResponseType {
            case presentSpaceRocket(_ : [SpaceRocketModel], metterings: [Item])
            case updateMetterings(metterings: [Item])
        }
    }
    struct ViewModel
    {
        enum viewModelData {
            case spaceRocket(_ : [SpaceRocketModel], metterings: [Item])
            case updateMetterings(metterings: [Item])
        }
    }
  }
}
