//
//  MainInteractor.swift
//  SpaceX Launches
//
//  Created by Vlad Ralovich on 5.04.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
    func doSomething(request: Main.Something.Request.RequestType)
}

protocol MainDataStore
{
    var model: [SpaceRocketModel] { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{
  var presenter: MainPresentationLogic?
  var worker: MainWorker?
  var model = [SpaceRocketModel]()
  
  // MARK: Do something
  
    func doSomething(request: Main.Something.Request.RequestType)
  {
    worker = MainWorker()
    worker?.doSomeWork()
      
      switch request {
      case .getSpaceRocket:
          let service: ServiceFetcherProtocol = ServiceFetcher()
          service.fetchSpaceRokets { result in
              self.model = result ?? [SpaceRocketModel]()
              self.presenter?.presentSomething(response: .presentSpaceRocket(result ?? [SpaceRocketModel]()))
          }   
      }
  }
}
